import type { DomainProfile } from './types.js';

/**
 * Industry / business segment profiles for insurance coverage analysis.
 *
 * Each profile describes a class of business, its typical coverage needs,
 * and the key risk factors that drive insurance purchasing decisions.
 */
export const INSURANCE_INDUSTRY_PROFILES: DomainProfile[] = [
  {
    id: 'technology-saas',
    name: 'Technology / SaaS',
    description:
      'Software-as-a-service companies, cloud platforms, and technology service providers. These businesses face significant technology E&O, cyber, and intellectual property exposures. Revenue is often subscription-based with high customer concentration risk. Many have remote/distributed workforces.',
    typicalCoverages: [
      'professional-liability',
      'cyber-liability',
      'cgl',
      'directors-officers',
      'epli',
      'bop',
      'umbrella-excess',
      'workers-compensation',
    ],
    riskFactors: [
      'Data breach and privacy liability from handling customer data',
      'Technology errors and omissions — software bugs causing client financial loss',
      'Intellectual property infringement claims',
      'Regulatory compliance (SOC 2, GDPR, CCPA, HIPAA if handling health data)',
      'Key person dependency and talent retention',
      'Rapid growth creating gaps in coverage adequacy',
      'Social engineering and funds transfer fraud targeting finance teams',
    ],
  },
  {
    id: 'professional-services',
    name: 'Professional Services / Consulting',
    description:
      'Firms providing advisory, consulting, accounting, engineering, architecture, or other professional services. The primary exposure is professional negligence — clients suing for financial loss caused by alleged errors in advice, design, or deliverables.',
    typicalCoverages: [
      'professional-liability',
      'cgl',
      'bop',
      'epli',
      'cyber-liability',
      'workers-compensation',
      'umbrella-excess',
      'commercial-auto',
    ],
    riskFactors: [
      'Professional negligence and errors in deliverables',
      'Breach of contract claims from dissatisfied clients',
      'Employee theft of confidential client information',
      'Regulatory changes affecting professional licensing',
      'Project delays leading to consequential damage claims',
      'Subcontractor performance failures creating vicarious liability',
    ],
  },
  {
    id: 'healthcare-provider',
    name: 'Healthcare Provider',
    description:
      'Hospitals, clinics, medical practices, home health agencies, and allied health providers. Healthcare businesses face medical malpractice, regulatory compliance (HIPAA), and employment practice exposures. Cyber liability is increasingly critical due to the value of protected health information.',
    typicalCoverages: [
      'professional-liability',
      'cgl',
      'commercial-property',
      'cyber-liability',
      'epli',
      'directors-officers',
      'workers-compensation',
      'commercial-auto',
      'umbrella-excess',
    ],
    riskFactors: [
      'Medical malpractice and patient injury claims',
      'HIPAA violations and protected health information breaches',
      'Medicare/Medicaid fraud and abuse allegations',
      'Workplace violence and employee safety',
      'Regulatory inspection and license revocation risk',
      'High employee turnover driving EPLI claims',
      'Ransomware attacks targeting healthcare IT systems',
    ],
  },
  {
    id: 'construction-general',
    name: 'Construction / General Contractor',
    description:
      'General contractors, specialty subcontractors, and construction management firms. Construction presents some of the highest liability exposures due to physical hazards, contractual obligations, and completed operations risks that can extend years after project completion.',
    typicalCoverages: [
      'cgl',
      'commercial-auto',
      'workers-compensation',
      'umbrella-excess',
      'commercial-property',
      'professional-liability',
      'business-interruption',
    ],
    riskFactors: [
      'Bodily injury to workers and third parties at job sites',
      'Property damage during construction and completed operations',
      'Contractual liability and additional insured requirements',
      'Defective workmanship claims emerging years after completion',
      'Subcontractor default and performance issues',
      'OSHA citations and regulatory penalties',
      'Equipment theft and damage on job sites',
    ],
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    description:
      'Companies that manufacture, process, or assemble physical products. Manufacturing businesses face product liability, property, and workers compensation as primary exposures. Supply chain disruptions and product recalls create significant business interruption risk.',
    typicalCoverages: [
      'cgl',
      'product-liability',
      'commercial-property',
      'business-interruption',
      'workers-compensation',
      'commercial-auto',
      'umbrella-excess',
      'cyber-liability',
    ],
    riskFactors: [
      'Product liability from defective products causing injury or damage',
      'Product recall expenses and reputational harm',
      'Large property values (buildings, equipment, inventory)',
      'Supply chain disruption and contingent business interruption',
      'Worker safety and ergonomic injury claims',
      'Environmental contamination and pollution liability',
      'Equipment breakdown causing production losses',
    ],
  },
  {
    id: 'retail-ecommerce',
    name: 'Retail / E-Commerce',
    description:
      'Brick-and-mortar retailers, online stores, and omni-channel businesses. Retail faces premises liability (slip-and-fall), product liability for goods sold, and cyber exposure from payment card processing. E-commerce businesses have additional technology and fulfillment risks.',
    typicalCoverages: [
      'cgl',
      'commercial-property',
      'bop',
      'product-liability',
      'cyber-liability',
      'business-interruption',
      'workers-compensation',
      'commercial-auto',
      'umbrella-excess',
    ],
    riskFactors: [
      'Premises liability (customer injuries, slip-and-fall)',
      'Product liability for goods manufactured by third parties',
      'Payment card data breaches (PCI-DSS compliance)',
      'Inventory loss from theft, fire, or natural disasters',
      'E-commerce platform outages causing revenue loss',
      'Delivery and fulfillment errors',
      'Seasonal revenue swings affecting business interruption values',
    ],
  },
  {
    id: 'financial-services',
    name: 'Financial Services',
    description:
      'Banks, insurance agencies, investment advisors, fintech companies, and other financial institutions. Financial services face professional liability, fiduciary liability, and regulatory compliance exposures. Cyber threats are particularly acute due to the financial data handled.',
    typicalCoverages: [
      'professional-liability',
      'directors-officers',
      'cyber-liability',
      'epli',
      'cgl',
      'commercial-property',
      'workers-compensation',
      'umbrella-excess',
    ],
    riskFactors: [
      'Professional negligence in financial advice or management',
      'Fiduciary liability for investment and retirement plan management',
      'Regulatory enforcement actions (SEC, FINRA, state regulators)',
      'Wire fraud and social engineering targeting financial transactions',
      'Data breach of sensitive financial information',
      'Securities class action lawsuits',
      'Anti-money laundering compliance failures',
    ],
  },
  {
    id: 'hospitality',
    name: 'Hospitality / Hotels / Restaurants',
    description:
      'Hotels, resorts, restaurants, bars, and entertainment venues. Hospitality faces high premises liability exposure from the public, liquor liability, food contamination risks, and significant property values. Seasonal and event-driven revenue creates business interruption challenges.',
    typicalCoverages: [
      'cgl',
      'commercial-property',
      'business-interruption',
      'workers-compensation',
      'commercial-auto',
      'umbrella-excess',
      'epli',
      'cyber-liability',
    ],
    riskFactors: [
      'Premises liability from high public foot traffic',
      'Liquor liability (assault, DUI, alcohol-related injuries)',
      'Foodborne illness and contamination claims',
      'Large property values with fire and natural disaster exposure',
      'High employee turnover and seasonal staffing',
      'Guest data privacy (PCI, personal information)',
      'Slip-and-fall claims from guests and delivery personnel',
    ],
  },
  {
    id: 'nonprofit',
    name: 'Nonprofit / Association',
    description:
      'Charitable organizations, trade associations, educational institutions, and social service agencies. Nonprofits face D&O liability from board decisions, volunteer injury exposure, and fundraising/fiduciary obligations. Budget constraints often lead to coverage gaps.',
    typicalCoverages: [
      'directors-officers',
      'cgl',
      'commercial-property',
      'epli',
      'professional-liability',
      'workers-compensation',
      'umbrella-excess',
      'cyber-liability',
    ],
    riskFactors: [
      'Board member personal liability for organizational decisions',
      'Volunteer injury and volunteer-caused injuries',
      'Donor and fund management fiduciary exposure',
      'Special event liability (galas, races, community events)',
      'Limited budgets creating pressure to underinsure',
      'Sexual abuse and misconduct claims (youth-serving organizations)',
      'Government grant compliance and audit risk',
    ],
  },
];
